Merged revisions 3043-3057 via svnmerge from http://svn.castleproject.org:8080/svn/castle/trunk
........
  r3043 | hammett | 2006-12-04 22:13:30 +0100 (ma, 04 dec 2006) | 14 lines
  
  - Applied patch by Andrew Peters fixing AR-97
    "Pluralization of table names"
    
    This patch introduces the pluralizeTableNames attribute on the configuration
    which, if set to true, pluralizes the ActiveRecord types tables where no name
    was specified.
    
    For example:
    
    [ActiveRecord]
    public class Student : ActiveRecordBase<Student>
    
    The table name will be infered as 'Students'
........
  r3044 | henry | 2006-12-05 03:04:43 +0100 (di, 05 dec 2006) | 1 line
  
  Resolved COMP-3: Add support for generic collections.
........
  r3045 | ayende | 2006-12-05 08:53:49 +0100 (di, 05 dec 2006) | 3 lines
  
  MR-173 - Ported Brail to C#.
  While all the tests are passing, I would like to get some feedback from the users about this yet.
........
  r3046 | roelofb | 2006-12-05 09:08:21 +0100 (di, 05 dec 2006) | 1 line
  
  Removed AssemblyInfo.cs and updated svn:ignore for Brail
........
  r3047 | roelofb | 2006-12-05 09:24:14 +0100 (di, 05 dec 2006) | 1 line
  
  COMP-3: Adds support for IList<T> interface.
........
  r3048 | roelofb | 2006-12-05 09:40:56 +0100 (di, 05 dec 2006) | 2 lines
  
  COMP-3: Fix check on types to ignore.
........
  r3049 | hammett | 2006-12-05 14:19:42 +0100 (di, 05 dec 2006) | 1 line
  
  Added null check on facility as suggested by Adam Mills
........
  r3050 | hammett | 2006-12-05 14:31:39 +0100 (di, 05 dec 2006) | 2 lines
  
  Added [Serializable] to Page/AbstractPage
........
  r3051 | henry | 2006-12-05 18:12:30 +0100 (di, 05 dec 2006) | 1 line
  
  Fixed MR-164: Allow and Exclude property acts on all objects, in any depth.
........
  r3053 | roelofb | 2006-12-06 17:45:13 +0100 (wo, 06 dec 2006) | 1 line
  
  Applied (modified) patch from Ernst Naezer, fixing FACILITIES-66.
........
  r3054 | roelofb | 2006-12-06 18:43:16 +0100 (wo, 06 dec 2006) | 1 line
  
  Changes due to FACILITIES-66 fix.
........
  r3055 | roelofb | 2006-12-07 00:37:57 +0100 (do, 07 dec 2006) | 4 lines
  
  Adapted to DP2, but has lots of failing tests because DP2 does not yet support it:
  - System.NotSupportedException : Cannot convert to ByRef types
  - System.ArgumentException : Target does not implement interface
  - no mixins
........
  r3056 | roelofb | 2006-12-07 02:13:04 +0100 (do, 07 dec 2006) | 2 lines
  
  Adapted to compile with new Windsor/DP2 but the build still fails due to failing tests on Aspect#. All other tests pass.
........
  r3057 | roelofb | 2006-12-07 02:31:54 +0100 (do, 07 dec 2006) | 1 line
  
  The facility changes
........


git-svn-id: http://svn.castleproject.org:8080/svn/castle/branches/1.0.x@4250 73e77b4c-caa6-f847-a29a-24ab75ae54b6